### ISSUE TITLE
Please allow to type in PIN when using an custom consumer key for twitter.

### ISSUE THREAD

**Issue by nyaathea** [TwidereProject/TwidereX-iOS#136]
I have an consumer key/consumer secret that takes you to the twitter website and tells you to type in a PIN for the app to get access to the api. TwidereX currently just skips it and when the PIN prompt comes up it just logs in anyways resulting in it not working correctly.

**Comment by MainasuK** [comment]
Hi @nyaathea. Please try the TestFlight v2.0.0
https://testflight.apple.com/join/GJIDXvW7

For your question. It's normal if the app to bring you to the home page after Twitter OAuth. You could just ignore the PIN code and the app will handle it automatically.

The app supports the custom API key, but you must pay for the Twitter developer Basic or Pro tier. Otherwise, in the free tier, you can only publish the post. Also, some features like home timeline and mention were removed due to tweet cap limitation. Finally, If you are an iOS developer try to build on the new v2 branch. We are sorry the core lib TwitterSDK is private now.
